config/routes.rb
Cscone::Application.routes.draw do

  

  resources :insurance_transactions do
  get 'export',:on=>:collection
end

 

  namespace :admin do resources :insurance_premia end
  
    namespace :admin do resources :reports do
      get 'banking',:on=>:collection
      get 'insurance',:on=>:collection
      get 'insurance_transaction',:on=>:collection
      get 'banking_transaction',:on=>:collection
      post 'banking_report',:on=>:collection
      post 'banking_transaction_report',:on=>:collection
      post 'insurance_report',:on=>:collection
      post  'insurance_transaction_report',:on=>:collection
    end
   end
  namespace :admin do resources :premia do
 get 'export',:on=>:collection
end
 end

  resources :transactions do
     get 'export',:on=>:collection
   end

  namespace :admin do resources :account_types do
 get 'export',:on=>:collection
end
end

  

  resources :insurances do
 get 'export',:on=>:collection
end

  resources :bankings do
     get 'export',:on=>:collection
     get 'edit_profile',:on=>:collection
     get 'show_profile',:on=>:collection
   end
 

  namespace :admin do resources :vle_representatives do
      get 'export',:on=>:collection
      get 'vle_user',:on=>:collection
      get 'vle_document',:on=>:collection
      get 'vle_report',:on=>:collection
       post 'load_bidding_zones',:on=>:collection
          post 'load_districts',:on=>:collection
          post 'load_csc_blocks',:on=>:collection
          post 'load_vle_representatives',:on=>:collection
        get 'disable_representative',:on=>:collection
        get 'update_vle_representative',:on=>:collection
        get 'vle_profile',:on=>:collection
         get 'edit_profile',:on=>:collection
        post 'csv_import' , :on=>:collection
         get 'upload', :on=>:collection 
         get 'reset_password',:on=>:collection
          get 'upload_password',:on=>:collection
          get 'report',:on=>:collection
          get 'bulk_mailing' , :on=>:collection
          

      end
  end

  namespace :admin do
       resources :vle_documents do
           get 'export',:on=>:collection
       end
        end

  namespace :admin do
      resources :csc_blocks do
          get 'export',:on=>:collection
          post 'load_bidding_zones',:on=>:collection
          post 'load_districts',:on=>:collection
          end
      end

  namespace :admin do
  resources :districts do
            get 'vle_document',:on=>:collection
      post 'load_bidding_zones',:on => :collection
  get 'export', :on=>:collection
       end
end
  namespace :admin do
  resources :bidding_zones do
    get 'export',:on=>:collection
    end
   end

  namespace :admin do
      resources :states do
          get 'export' ,:on=>:collection
           post 'csv_import', :on=>:collection
  get 'upload', :on=>:collection 
       end

      end
  
    resources :user_sessions
    
 namespace :admin do
 resources :users do
  get 'export',:on=>:collection
    end

  end
  resource :accout,:controller=>'users'
  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  root :to => "user_sessions#new"

   match ':controller(/:action(/:id(.:format)))'
end

app/models/user.rb
class User < ActiveRecord::Base
 acts_as_authentic
  has_many :assignments
  has_many :bankings,:dependent=>:destroy
   has_many :insurances,:dependent=>:destroy
 has_many :insurance_transactions,:dependent=>:destroy
   has_many :transactions,:dependent=>:destroy
  has_many :roles, :through => :assignments
  has_one :vle_representative_profile
  accepts_nested_attributes_for :vle_representative_profile
  has_many :vle_documents
 validates :name,:presence => true
  def role_symbols
    roles.map do |role|
      role.name.underscore.to_sym
    end
  end

  STATUS_TYPES = [
  #[ Displayed,stored in db]
  [ "On Hold" , "On Hold" ],
  [ "Approved" , "Approved" ],
  [ "Blocked" , "Blocked" ]
  ]

     def self.search(search)
    if search
      where(:name.matches => "%#{search}%") #from meta_where gem
    else
      scoped
    end
  end
end

app/controllers/admin/vle_representatives_controller.rb
require 'fastercsv'
require 'csv'
class Admin::VleRepresentativesController < ApplicationController

  helper_method :sort_column, :sort_direction
  layout 'admin'
  before_filter :require_user
  before_filter :recent_items
  
 
  def index
    role = Role.find_by_name('vle_representative')
    @vle_users = role.users.order.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page =>page,:per_page=>per_page )

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @vle_users }
    end
  end

  def show
    @vle_user =  User.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @vle_representative }
    end
  end
  

  def new
    @user = User.new
    @user.build_vle_representative_profile
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml =>  @user }
    end
  end
  

  def edit
    @user = User.find(params[:id])
    # @vle_user.build_vle_representative_profile
  end
  

  def create
    @user = User.new(params[:user])
    @user.created_by = @created_by
    respond_to do |format|
      if @user.save
        format.html { redirect_to({:controller=>'vle_representatives',:action=>'new'}, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @vle_user, :status => :created, :location => @vle_representative }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end
    
  def update
    @user = User.find(params[:id])
    @user.updated_by = @updated_by
    respond_to do |format|
      if @user.update_attributes(params[:user])
        
        format.html { redirect_to({:action=>'show',:id=>@user.id
          }, :notice => 'Vle representative was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @vle_representative.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  
  def destroy
    @vle_user= User.find(params[:id])
    @vle_user.destroy
    respond_to do |format|
      format.html { redirect_to(admin_vle_representatives_url) }
      format.xml  { head :ok }
    end
  end
  
  def vle_document
    @vle_documents = VleDocument.all
    #@vle_documents = VleDocument.all
  end
  
  def vle_profile
    role = Role.find_by_name('vle_representative')
    @vle_users = role.users.order(sort_column + " " + sort_direction).paginate(:page =>page,:per_page=>per_page )
  end
  
  def disable_representative
      role = Role.find_by_name('vle_representative')
     @users = role.users.order.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page =>page,:per_page=>per_page )
#     @users = User.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page =>page,:per_page=>per_page )
    
   end 
   
  def update_status
    @user = User.find(params[:id])
    status = @user.status
    @user.update_attribute('status',params[:status])
    flash[:success] = "#{@user.name}  has been updated from #{status} to #{@user.status}"
   
    respond_to do |format|
      format.html{redirect_to(admin_users_path) }
      format.xml  { render :xml => @degree.errors, :status => :unprocessable_entity  }
    end
  end
  
  def update_vle_representative
   puts "#############  #{params[:user_vle_representative_profile_attributes][:user_id]}"
  end
  
  
  def reset_password
    @user = User.find(params[:id])
    @user.password= @user.password_confirmation=@user.email
   respond_to do |format|
      if @user.update_attributes(params[:user])
        
        format.html { redirect_to({:action=>'upload_password',:id=>@user.id
          }, :notice => 'VLE Representative password is  successfully Reset.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @vle_representative.errors, :status => :unprocessable_entity }
      end
    end
    # @vle_user.build_vle_representative_profile
  end
  
 def upload_password
  role = Role.find_by_name('vle_representative')
     @users = role.users.order.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page =>page,:per_page=>per_page )
  end
 
  def csv_import
   @vle_user=CSV::Reader.parse(params[:upload][:file])
   n=0
   @vle_user.each do |row|
   user = User.create do |u|
       u.name  =row[0]
       u.email = row[1]
      u.password = u.password_confirmation = row[1]
      u.phone_number = row[2]
      u.status = 'Approved'
      u.created_by = 1
      u.updated_by=1
    end
    if user.save
   Assignment.create(:user_id=>user.id,:role_id=>3,:created_at=>Time.now,:updated_at=>Time.now)        
    c=VleRepresentativeProfile.new  
    c.state_id= 1 
    c.user_id = user.id
    bidding_zone = BiddingZone.find_by_name(row[4].strip)
    c.bidding_zone_id=bidding_zone.id
    district=District.find_by_name(row[5].strip)
    c.district_id =district.id
    csc_block=CscBlock.find_by_name(row[6].strip)
    c.csc_block_id = csc_block.id
    c.father_name=row[7]
    c.address=row[8]
    c.pincode=row[9]
    c.csc_panchayat=row[10]
   if  c.save!
    n=n+1
    GC.start if n%50==0
    flash[:notice]= "The  #{n} Records are imported sucessfully"
       end
      end
    end
  end
  
  def upload
  end
  
  
  def load_bidding_zones
    @bidding_zones = BiddingZone.where(:state_id => params[:id])
    render :update do |page|
 page[:user_vle_representative_profile_attributes_bidding_zone_id].replace collection_select(:user_vle_representative_profile_attributes,:bidding_zone_id, @bidding_zones, :bidding_zone.id, :name,{:prompt=>'Select Bidding Zone'},
      { :onchange=>"#{remote_function(:url=>{:action=>'load_districts'},:with =>"'id='+value")}" })
    end
  end
  
  def load_districts
    @districts = District.where(:bidding_zone_id => params[:id])
    render :update do |page|
      page[:user_vle_representative_profile_attributes_district_id].replace collection_select(:user_vle_representative_profile_attributes,:district_id, @districts, :district.id, :name,{:prompt=>'Select district'},
      { :onchange=>"#{remote_function(:url=>{:action=>'load_csc_blocks'},:with =>"'id='+value")}" })
    end
  end
  
  def load_csc_blocks
    @csc_blocks = CscBlock.where(:district_id => params[:id])
    render :update do |page|
      page[:user_vle_representative_profile_attributes_csc_block_id].replace collection_select(:user_vle_representative_profile_attributes,:csc_block_id, @csc_blocks, :csc_block.id, :name,{:prompt=>'select CSCblock'})
#,
 #     :onchange=>"#{remote_function(:url=>{:action=>'load_vle_representatives'},:with =>"'id='+value")}")
    end
  end
  
 
  def export
    @vle_users = Role.find_by_name('vle_representative').users#User.search(params[:search]).order("name")
    outfile = "vle_representatives" + Time.now.strftime("%d-%m-%Y-%H-%M-%S") + ".csv"
      csv_data = FasterCSV.generate do |csv|
      csv << ["Name","Email","Father Name","Address","Pincode","Date Of Biirth","CSC Panchayath","Create at","Created By"]
      @vle_users.each do |vle_user|
        csv << [vle_user.name,vle_user.email,vle_user.vle_representative_profile.father_name,vle_user.vle_representative_profile.address,vle_user.vle_representative_profile.pincode,vle_user.vle_representative_profile.date_of_birth,vle_user.vle_representative_profile.csc_panchayat ,vle_user.created_at.strftime('%d-%m-%Y %H:%M:%S'),User.find(vle_user.created_by).name]
      end
    end
    send_data csv_data,
    :type => 'text/csv; charset=iso-8859-1; header=present',
    :disposition => "attachment; filename=#{outfile}"
    
  end

  def vle_report
	role = Role.find_by_name('vle_representative')
    @vle_users = role.users
 	@reports = Banking.where(:created_by=>params[:id])

  end
  
  def bulk_mailing
   role = Role.find_by_name('vle_representative')
    @vle_users = role.users
    @districts=District.all
  end
  private
  
  def recent_items
    @recent_vle_users = User.find(:all,:limit=>10,:order=>'created_at DESC')
  end
  
  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
  
end

app/helpers/admin/vle_representatives_helper.rb
module Admin::VleRepresentativesHelper
end

app/views/admin/vle_representatives/_form.html.erb
<div class="form-container">
    <%= form_for(@user,:url=>{:action=>'create'},:html=>{:class=>'cmxform'}) do |f| %>
   
    <p class="legend">
        <strong>Note:</strong>
        Required fields are marked with an asterisk (<em>*</em>)
    </p>
    <fieldset>
        <legend>
            <%= User %>
        </legend>
        <%= f.error_messages %>
        <div>
            <label for="name">
                Name<em>*</em>
            </label>
            <%= f.text_field :name %>
        </div>
        <div>
            <label for="email">
                Email <em>*</em>
            </label>
            <%= f.text_field :email %>
        </div>
        <div>
            <label for="password">
                Password <em>*</em>
            </label>
            <%= f.password_field :password %>
        </div>
        <div>
            <label for="password_confirmation">
                Password Confirmation
            </label>
            <%= f.password_field :password_confirmation %>
        </div>
        <div>
            <label for="phone_number">
                Mobile Number
            </label>
            <%= f.text_field :phone_number %>
        </div>
        <div>
            <label for="status">
                Status
            </label>
            <%=f.select :status,User::STATUS_TYPES,:prompt => "-----Select a Status-----" %>
            <br/>
        </div>
        <div>
            <label for="roles">
                Roles
            </label>
            <% for role in Role.where(:name=>'vle_representative') %>
            <%= check_box_tag "user[role_ids][]", role.id, @user.roles.include?(role) %>
            <%=h role.name %>
            <% end %>
        </div>
        <%= f.fields_for :vle_representative_profile do |profile| %>
        <div>
            <label "state_id">
 State Name
            </label>
            <%= profile.collection_select :state_id, State.order('name'), :id, :name ,{:prompt=>'Select State'},{ :onchange=>"#{remote_function(:url=>{:action=>'load_bidding_zones'},:with =>"'id='+value")}" } %>
        </div>
        <div>
            <label for="bidding_zone_id">
                Bidding Zone Name<em>*</em>
            </label>
            <%= profile.collection_select :bidding_zone_id,BiddingZone.all, :id, :name,{:prompt =>'Select Bidding Zone'} %>
        </div>
        <div>
            <label for="district_id">
                District Name<em>*</em>
            </label>
            <%= profile.collection_select :district_id, District.all,:id, :name,{:prompt =>'Select District'} %>
        </div>
        <div>
            <label for="csc_block_id">
                CSC Name
            </label>
            <%= profile.collection_select :csc_block_id, CscBlock.all,:id, :name,{:prompt =>'Select CSC Block'} %>
        </div>
        <div>
            <label for="father_name">
                Father Name<em>*</em>
            </label>
            <%= profile.text_field :father_name %>
        </div>
        <div>
            <label for="address">
                Address<em>*</em>
            </label>
            <%= profile.text_field :address %>
        </div>
        <div>
            <label for="pincode">
                Pincode<em>*</em>
            </label>
            <%= profile.text_field :pincode %>
        </div>
        <div>
            <label for="date_of_birth ">
                Date Of Birth <em>*</em>
            </label>
            <%= profile.date_select:date_of_birth,:start_year => 1940 %>
        </div>
        <div>
            <label for="csc_panchyath ">
                CSC Panchyath <em>*</em>
            </label>
            <%= profile.text_field :csc_panchayat %>
        </div>
       
        <% end %>
        <div class="buttonrow">
            <%= f.submit button_name ,:class=>'button' %>
        </div>
    </fieldset>
    <% end %>


app/views/admin/vle_representatives/_recent_items.html.erb
<% for vle_user in @recent_vle_users  %>
<li class="" id="recent_vle_user_<%= vle_user.id%>">
    <dt>
        <%=link_to truncate(vle_user.name,:length=>27),admin_vle_representative_path(vle_user) %>
    </dt>
    <tt>
        <br/>
    </tt>
</li>
<% end %>


app/views/admin/vle_representatives/_vle_user.html.erb
<% for vle_user in @vle_users -%>
<tr>
<td>
<%= link_to(highlight(vle_user.name,params[:search]),admin_vle_representative_path(vle_user)) %>
</td>

<td>
 <%=h vle_user.email %>
</td>
<td>
 <%=h vle_user.vle_representative_profile.state.name %>
</td>
<td>
 <%=h vle_user.vle_representative_profile.bidding_zone.name %>
</td>
<td>
 <%=h vle_user.vle_representative_profile.district.name %>
</td>
<td>
 <%=h vle_user.vle_representative_profile.csc_block.name %>
</td>
<td>
 <%=h vle_user.vle_representative_profile.address %>
</td>
<td>
 <%=h vle_user.vle_representative_profile.pincode %>
</td>
<td>
 <%=h vle_user.phone_number %>
</td>
<td>
 <%=h vle_user.vle_representative_profile.csc_panchayat %>
</td>
<td>
 <%=h vle_user.status %>
</td>

<td>
    <%= link_to 'Edit', edit_admin_vle_representative_path(vle_user) %> |
    <%= link_to 'Delete', [:admin,vle_user], :confirm => 'Are you sure?', :method => :delete %> |
    <%= link_to 'View', :action=>'show',:id=>vle_user.id %>
</td>
</tr>

<% end %>



app/views/admin/vle_representatives/disable_representative.html.erb
<div id="user_list" class="list">
<%if @users.blank?%>
<b><i> There are No Users yet..!</i></b> 
<%else%>
<table width="100%">
	<tr><td align="left"><h3 align="left"><%=@table_heading ||= 'Listing VLE Representatives'%></h3></td>
           <td align="right">
                <b><i>per page</i></b>
                    <%=per_page %> |  <%= page_entries_info @users %>
            </td>	   
	</tr>
</table>
<table class="tablesorter" cellspacing="1">
	<thead>
	<tr>
		<th>Status</th>
		<th><%= sortable "role" %></th>
		<th><%= sortable "name" %></th>		
		<th><%= sortable "Email"%></th>	
		<th>Actions</th>
	</tr>
	</thead>
	<%  for user in @users %>
	<tr>
 <td><%=model_status user %></td>
 <td><%= user.roles[0].name%></td>
 <td> <%= link_to(highlight(user.name,params[:search]),admin_user_path(user)) %></td>
 <td><%=h user.email %></td>
 <td> <%=link_to_model_status user %> 
 </td> 	
</tr>
<% end %>

 <% end %>
</table>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
     <%= will_paginate @users %>
</div>

app/views/admin/vle_representatives/edit.html.erb
<div class="form-container">
    <%= form_for(@user,:url=>{:action=>'update'},:html=>{:class=>'cmxform'}) do |f| %>
    <%=render :partial=>'form',:locals=>{:f=>f,:button_name=>'Update',:heading=>'Edit VLE Profile'} %>
    <% end %>
    </div>


<div class="bottom_links">
    
    <a href="/admin/vle_representatives" class="more">&larr; All VLE Profile</a>

    <%= link_to 'Show',{:action=>'show',:id=>@user.id},:class=>'more'%>
    
</div>

app/views/admin/vle_representatives/index.html.erb
<div id="markets">
    <%=render :partial=>'results' %>
</div>

app/views/admin/vle_representatives/new.html.erb
<div class="form-container">
    <%= form_for(@user,:url=>{:action=>'create'},:html=>{:class=>'cmxform'}) do |f| %>
    <%=render :partial=>'form',:locals=>{:f=>f,:button_name=>'create',:heading=>'New VLE Profile'} %>
    <% end %>
    </div>

<div class="bottom_links">
    <a href="/admin/vle_representatives" class="more">&larr; List All Users</a>
</div>

app/views/admin/vle_representatives/show.html.erb
<div class="form-container">
  <fieldset>
        <legend>
            <b><%= @vle_user.name %></b>
        </legend>
        <div>
            <label>
                <b>Name:</b>
            </label>
            <%=h @vle_user.name%>
        </div>
        <hr/>
        <div>
            <label>
                <b>Email:</b>
            </label>
            <%=h @vle_user.email%>
        </div>
        <hr/>
         <div>
            <label>
                <b>State:</b>
            </label>
            <%=h @vle_user.vle_representative_profile.state.name %>
        </div>
        <hr/>
         <div>
            <label>
                <b>Bidding Zone:</b>
            </label>
          <%=h @vle_user.vle_representative_profile.bidding_zone.name %>
        </div>
        <hr/>
         <div>
            <label>
                <b>District:</b>
            </label>
            <%=h @vle_user.vle_representative_profile.district.name %>
        </div>
        <hr/>
         <div>
            <label>
                <b>CSC Block:</b>
            </label>
           <%=h @vle_user.vle_representative_profile.csc_block.name %>
        </div>
        <hr/>
         <div>
            <label>
                <b>Phone Number:</b>
            </label>
            <%=h @vle_user.phone_number %>
        </div>
        <hr/>
         <div>
            <label>
                <b>Father Name:</b>
            </label>
            <%=h @vle_user.vle_representative_profile.father_name %>
        </div>
        <hr/>
        <div>
            <label>
                <b>Address:</b>
            </label>
            <%=h @vle_user.vle_representative_profile.address %>
        </div>
        <hr/>
        <div>
            <label>
                <b>Pincode:</b>
            </label>
            <%=h @vle_user.vle_representative_profile.pincode %>
        </div>
        <hr/>
        <div>
            <label>
                <b>Date Of Birth:</b>
            </label>
            <%=h @vle_user.vle_representative_profile.date_of_birth %>
        </div>
        <hr/>
        <div>
            <label>
                <b>CSC Panchyath:</b>
            </label>
            <%=h @vle_user.vle_representative_profile.csc_panchayat %>
        </div>
        <hr/>
         <div>
            <label>
                <b>Created by:</b>
            </label>
            <%= User.find(@vle_user.created_by).name %>
        </div>
        <hr/>
<div class="bottom_links">
    <a href="/admin/vle_representatives" class="more">&larr; All VLE Representatives</a>
    &nbsp;&nbsp;
    <%= link_to edit_admin_vle_representative_path(@vle_representative),:class=>'more' do %>
    Edit &uarr;
    <% end %>
    &nbsp;&nbsp;
    <%=link_to new_admin_vle_representative_path,:class=>'more' do %>
    Create New VLE Representative &rarr;

    <% end %>
</div>

app/views/admin/vle_representatives/upload_password.html.erb
<div id="user_list" class="list">
<%if @users.blank?%>
<b><i> There are No Users yet..!</i></b> 
<%else%>
<table width="100%">
	<tr><td align="left"><h3 align="left"><%=@table_heading ||= 'Listing VLE Representatives'%></h3></td>
           <td align="right">
                <b><i>per page</i></b>
                    <%=per_page %> |  <%= page_entries_info @users %>
            </td>	   
	</tr>
</table>
<table class="tablesorter" cellspacing="1">
	<thead>
	<tr>
		<th><%= sortable "name" %></th>		
		<th><%= sortable "Email"%></th>	
		<th class="{sorter: false}">Reset</th>
	</tr>
	</thead>
	<%  for user in @users %>
	<tr>
  <td> <%= link_to(highlight(user.name,params[:search]),admin_user_path(user)) %></td>
 <td><%=h user.email %></td>
 <td><%=link_to "Reset Password",:action=>'reset_password',:id=>user.id %></td>
</tr>
<% end %>
 <% end %>
</table>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
     <%= will_paginate @users %>
</div>

app/views/admin/vle_representatives/vle_document.html.erb
<div id="vle_document_list" class="list">
    <%if @vle_documents.blank? %>
    <div class="empty">
        There are no VLE Documents yet..!
    </div>
    <%else %>
    <table width="100%">
        <tr>
            <td align="left">
                <h3 align="left"><%=@table_heading ||= 'Listing VLE Documents' %></h3>
            </td>
            <td align="right">
                <b><i>per page</i></b>
                <%=per_page %>| 
            </td>
        </tr>
    </table>
    <table class="tablesorter" cellspacing="1">
        <thead>
            <tr>
            	<th>
                    Representative Name
                </th>
                <th>
                    Agreement Paper
                </th>
                
                <th>
                    Address Proof
                </th>
                <th>
                    Education Proof
                </th>
                <th>
                    Photograph Proof
                </th>
                
                <th>
                    DD Date
                </th>
				<th>
                    DD Number
                </th>
                <th>
                    DD Bank Name
                </th>
                <th>
                    DD Branch Name
                </th>
                <th>
                    DD Amount
                </th>
                <th>
                    Created By
                </th>
                <th>
                    Created At
                </th>
                <th>
                    &nbsp;
                </th>
            </tr>
        </thead>
        <% for vle_document in @vle_documents %>
        <tr>
            <td>
                <%=link_to(highlight(vle_document.user.name,params[:search]),admin_vle_document_path(vle_document)) %>
            </td>
			 <td>
                <%=h vle_document.agreement_paper %>
            </td>
            <td>
                <%=h vle_document.address_proof %>
            </td>
            <td>
                <%=h vle_document.education_proof %>
            </td>
            <td>
                <%=h vle_document.photograph_proof %>
            </td>
            <td>
                <%=h vle_document.dd_number %>
            </td>
            <td>
                <%=h vle_document.dd_date %>
            </td>
            <td>
                <%=h vle_document.dd_bank_name %>
            </td>
            <td>
                <%=h vle_document.dd_branch_name %>
            </td>
            <td>
                <%=h vle_document.dd_amount %>
            </td>
            <td>
                <%=h @created_name %>
            </td>
            <td>
                <%=h vle_document.created_at.strftime('%d-%m-%Y %H:%M:%S') %>
            </td>
            <td>
                <%= link_to 'Edit', edit_admin_vle_document_path(vle_document) %>|<%= link_to 'Destroy', [:admin,vle_document], :confirm => 'Are you sure?', :method => :delete %>|<%= link_to 'Show', [:admin,vle_document] %>
            </td>
        </tr>
        <% end %>
    </table>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
   
    <% end %>
</div>

app/views/admin/vle_representatives/vle_report.html.erb
<div id="vle_representative_list" class="list">
    <%if @vle_users.blank? %>
    <div class="empty">There are no VLE Representatives yet..!</div>
    <%else %>
    <table width="100%">
        <tr>
            <td align="left">
                <h3 align="left"><%=@table_heading ||= 'Listing VLE Reports' %></h3>
            </td>
            
        </tr>
    </table>
    <table class="tablesorter" cellspacing="1">
        <thead>
            <tr>

                <th>
               <%= sortable 'name' %>
                </th>
                <th>
               <%= sortable 'email' %>
                </th>
              
                <th>
               <%= sortable 'biddingZoneName' %>
                </th>

                <th>
                    <%= sortable 'districtname' %>
                </th>
                <th>
                   <%= sortable 'cscblockname' %>
                </th>
                <th>
                   <%= sortable 'Bankings' %>
                </th>
                 <th>
                   <%= sortable 'Bank Transactions' %>
                </th>
                 <th>
                   <%= sortable 'Insurances' %>
                </th>
                 <th>
                   <%= sortable 'Insurance Transactions' %>
                </th> 
             </tr>
        </thead>
        <% for vle_user in @vle_users -%>
<tr>
<td>
<%=link_to(highlight(vle_user.name,params[:search]),admin_vle_representative_path(vle_user)) %>
</td>

<td>
 <%=h vle_user.email %>
</td>
<td>
 <%=h vle_user.vle_representative_profile.bidding_zone.name %>
</td>
<td>
 <%=h vle_user.vle_representative_profile.district.name %>
</td>
<td>
 <%=h vle_user.vle_representative_profile.csc_block.name %>
</td>
<td>
 <%=vle_user.bankings.size%>
</td>
<td>
 <%=vle_user.transactions.size%>
</td>
<td>
 <%=vle_user.insurances.size%>
</td>
<td>
 <%=vle_user.insurance_transactions.size%>
</td>
</tr>
<% end %>
<% end %>
</table>
</div>